# Generated by Django 5.1.2 on 2024-10-21 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0003_alter_menu_category_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('day', models.CharField(max_length=20)),
                ('seats', models.IntegerField()),
            ],
        ),
    ]
